### PR TITLE
Postprocess eval bugfix

### PR DESCRIPTION
**Pull request by bnp26**
Fixed up issue when creating new_context.

### CODE REVIEW

**Comment by pymonger** [comment]
@bnp26: I'll defer to @mcayanan and @NamrataM on this.

**Review by pymonger — COMMENTED** [review]
@bnp26: could you also bump the version as well to `2.1.2`?

**Comment by mcayanan** [comment]
I think this change is good, but I'd like @NamrataM input on this since she's more familiar with the post processor than me.

**Review by NamrataM — DISMISSED** [review]

**Comment by pymonger** [comment]
@NamrataM: could you review this? you're the cognizant person on the post processing.

**Review by NamrataM — APPROVED** [review]
LGTM! Thanks @bnp26

**Pull request merged**
