### PR TITLE
fix for accessing job_result in post processor

### PR DESCRIPTION
**Pull request by NamrataM**
self.job_result to be self._job_result

### CODE REVIEW

**Comment by mcayanan** [comment]
@NamrataM when you can, could you please create a Jira ticket for this on the HySDS Core side?

**Comment by NamrataM** [comment]
@mcayanan Yes will do.

**Comment by NamrataM** [comment]
Sorry for the quick merge. Needed to test things on NISAR.

**Comment by mcayanan** [comment]
No problem. As an alternative, to test things prior to merging, you could temporarily do the following in the nisar dockerfile:

- delete the core chimera directory
- clone the core chimera from github
- checkout the feature branch
- pip install -e .

```
rm -rf ~/verdi/ops/chimera
git clone http://github.com/hysds/chimera.git \
cd chimera
git checkout -b <BRANCH>
pip install -e .
```

**Pull request merged**
